# Generated by Django 4.0.4 on 2022-05-14 15:51

from django.db import migrations, models

def populate_sections(apps, schemaeditor):
    sections =[
            {
                "Advice": "Guids to a multitude of things that can help you as a parent",             
            },
            {
                "Stories": "Real stories from readers all over the world",               
            },
            {
                "Things to do": "Things to consider that may be of intrest to your growing child based on age",             
            },
            {
                "Reads": "Readings that may be of intrest. ",               
            }
        ]
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
    ]
